spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:mapper/*/*.xml
  config-location: classpath:mybatis-config.xml
swagger:
  enable: true
